config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users,
    path: "",
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      password: 'password',
      confirmation: 'verification',
      unlock: 'unlock',
      registration: 'register',
      sign_up: 'signup'
    }, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }

  root to: "home#index"

  get "/about", to: "home#about", as: "about_page"
  get "/dashboard", to: "dashboard#index", as: "dashboard_page"
  post "/leave_account", to: "accounts#leave_account", as: "leave_account"
  post "/main_account", to: "accounts#main_account", as: "main_account"
  post "/entry_paid", to: "entries#entry_paid", as: "entry_paid"
  get "/index", to: "home#index", as: "index_page"
  get "/resources", to: "home#resources", as: "resources_page"

  resources :accounts, only: [:index, :new, :create, :update, :destroy]
  resources :categories, only: [:new, :edit, :create, :update, :destroy]
  resources :contact_forms, only: [:index, :show, :create]
  resources :entries
  resources :reports, only: [:index]
  resources :settings, only: [:index]
  resources :tutorials, only: [:index, :show]

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/views/layouts/landing/_footer.html.erb
<footer class="bg-dark">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h4 class="section-heading">Gênese</h4>
      </div>

      <div class="col-lg-12 text-center">
        <%= link_to 'Inicio', root_path %>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to 'Vantagens', resources_page_path %>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to 'Sobre', about_page_path %>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to 'Contato', contact_forms_path %>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to 'Ajuda', tutorials_path %>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to 'Login', new_user_session_path %>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to 'Cadastrar', new_user_registration_path %>
        <br><br>
      </div>

      <div class="col-lg-12 text-center">
        <h5 class="section-heading">© 2015 - Sistema Gênese</h5>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/landing/_nav.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to 'Gênese', root_path, class: 'navbar-brand page-scroll' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to "Sair", destroy_user_session_path, method: :delete, class: 'navbar-link' %>
          </li>
          <li>
            <%= link_to dashboard_page_path, class: 'navbar-link' do %>
              Olá, <%= current_user.name %>
              <small> - Entre</small>
            <% end -%>
          </li>
        <% else %>
          <li>
            <%= link_to "Login", new_user_session_path, class: 'navbar-link' %>
          </li>
          <li>
            <%= link_to "Cadastre-se", new_user_registration_path, class: 'navbar-link' %>
          </li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav">
        <li><%= link_to 'Início', index_page_path %></li>
        <li><%= link_to 'Vantagens', resources_page_path %></li>
        <li><%= link_to 'Sobre', about_page_path %></li>
        <li><%= link_to 'Contato', contact_forms_path %></li>
        <li><%= link_to 'Ajuda', tutorials_path %></li>
      </ul>
    </div>
  </div>
</nav>