config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users,
    path: "",
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      password: 'password',
      confirmation: 'verification',
      unlock: 'unlock',
      registration: 'register',
      sign_up: 'signup'
    }, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }

  root to: "home#index"

  get "/about", to: "home#about", as: "about_page"
  get "/dashboard", to: "dashboard#index", as: "dashboard_page"
  post "/leave_account", to: "accounts#leave_account", as: "leave_account"
  post "/main_account", to: "accounts#main_account", as: "main_account"
  post "/entry_paid", to: "entries#entry_paid", as: "entry_paid"
  get "/index", to: "home#index", as: "index_page"
  get "/resources", to: "home#resources", as: "resources_page"

  resources :accounts, only: [:index, :new, :create, :update, :destroy]
  resources :categories, only: [:new, :edit, :create, :update, :destroy]
  resources :contact_forms, only: [:index, :show, :create]
  resources :entries
  resources :reports, only: [:index]
  resources :settings, only: [:index]
  resources :tutorials, only: [:index, :show]

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/account.rb
class Account < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :entries, dependent: :destroy
  has_many :categories, dependent: :destroy

  enum currency_type: { dollar: "en", euro: "es", real: "pt-BR" }
  enum entries_order: { crescent: true, decrescent: false }

  validates :currency_type, :name, :owner, presence: true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:destroy]
  respond_to :html, :json

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = current_user.accounts
    respond_with(@accounts)
  end

  # GET /accounts/new
  def new
    @account = current_user.accounts.new
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @user = current_user

    if account_params[:public] == '1' && params[:account][:users].present?
      @account = Account::SaveAccountService.new(@user, account_params, params[:account][:users]).save
    else
      @account = @user.accounts.create!(account_params)
    end

    if @account
      User::CategoryService.new(@account).create_categories
    end

    respond_to do |format|
      if @account
        format.html { redirect_to accounts_path, notice: I18n.t('activerecord.messages.account_created') }
        format.json { render :index, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    @current_account = current_account

    respond_to do |format|
      if @current_account.update(update_params)
        format.html { redirect_to settings_path, notice: I18n.t('activerecord.messages.account_updated') }
        format.json { render settings_path, status: :ok, location: @current_account }
      else
        format.html { render settings_path }
        format.json { render json: @current_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    flash = Account::DestroyAccountService.new(current_user, @account).destroy
    respond_to do |format|
      format.html { redirect_to accounts_path, flash }
      format.json { head :no_content }
    end
  end

  # POST /leave_account
  # POST /leave_account.json
  def leave_account
    account_id = params[:account_id]
    account = Account.find(account_id)
    unlinked_account = current_user.accounts.delete(account)

    if current_user.main_account == unlinked_account.id
      current_user.update(main_account: current_user.accounts.first.id)
    end

    respond_to do |format|
      format.html { redirect_to accounts_path, notice: I18n.t('activerecord.messages.account_unlinked') }
      format.json { render json: {url: accounts_path} }
    end
  end

  # POST /main_account
  # POST /main_account.json
  def main_account
    account_id = params[:account_id]

    respond_to do |format|
      if current_user.update(main_account: account_id.to_i)
        format.html { redirect_to dashboard_page_path, notice: I18n.t('activerecord.messages.main_account_updated') }
        format.json { render json: {url: dashboard_page_path} }
      else
        format.html { render :index }
        format.json { render json: current_user.errors }
      end
    end
  end

  private
  def set_account
    @account = Account.find(params[:id])
  end

  def account_params
    params.require(:account).permit(
      :name,
      :owner,
      :public,
      :currency_type,
      :entries_order,
      :reminder_active,
      :reminder_days_before
    )
  end

  def update_params
    params.require(:account).permit(
      :entries_order,
      :currency_type,
      :reminder_days_before,
      :reminder_active
    )
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/views/accounts/_form.html.erb
<%= simple_form_for(@account) do |f| %>
  <div class="row">
    <div class="col-xs-12">
      <%= f.error_notification %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <%= f.input :name, required: true %>
      <%= f.hidden_field :owner, :value => current_user.id %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <div class="form-group">
        <%= f.label :currency_type, class: 'control-label' %>
        <div>
          <%= f.input_field :currency_type, as: :radio_buttons, item_wrapper_tag: false, item_label_class: 'radio-inline' %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <%= f.input :reminder_active, input_html: {class: 'reminder_active'} %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <%= f.input :reminder_days_before, collection: 0..5, input_html: {include_blank: false, class: "reminder_days_before", disabled: (!@account.reminder_active)} %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <%= f.input :public, input_html: {class: 'public'} %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <%= f.input :users, collection: User.all.where.not(id: current_user.id), input_html: { multiple: true, class: 'select_users', disabled: (!@account.public)} %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-6">
      <%= link_to :back, class: 'btn btn-default' do %>
        <i class="fa fa-chevron-left"></i>
        Voltar
      <% end %>
    </div>
    <div class="col-xs-6 text-right">
      <%= f.button :submit, class: 'btn-success' %>
    </div>
  </div>
<% end %>

app/views/accounts/index.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h3>Contas</h3>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-8 col-lg-offset-2">
            <ul class="list-group">
              <% @accounts.each do |account| %>
                <li class="list-group-item account__item">
                  <% if current_user.main_account == account.id %>
                    <i class="fa fa-check fa-lg"></i>
                  <% end %>
                  <%= link_to account.name, main_account_path(account_id: account.id), method: :post, class: 'account__link' %>

                  <% if account.public && account.owner != current_user.id %>
                    <%= link_to leave_account_path(account_id: account.id), method: :post, class: 'account__link account__icon', title: 'Desvincular conta', data: {toggle: 'tooltip', placement: 'bottom', confirm: 'Você tem certeza que quer se desvincular desta conta?'} do %>
                      <i class="fa fa-sign-out"></i>
                    <% end %>
                  <% end %>

                  <small class="account__badge">
                    <% if account.public %>
                      <i class="fa fa-unlock-alt"></i>
                      Pública
                    <% else %>
                      <i class="fa fa-lock"></i>
                      Privada
                    <% end %>
                  </small>
                </li>
              <% end %>
            </ul>

            <%= link_to new_account_path, class: 'btn btn-default' do %>
              <i class="fa fa-plus"></i>
              Nova Conta
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/accounts/new.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="row">
          <div class="col-xs-12 text-center">
            <h3>Nova Conta</h3>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-12 col-sm-8 col-sm-offset-2">
            <%= render 'form' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>